version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  # gromozeka:
  #   build: .
  #   restart: always
  #   environment:
  #     - TG_BOT_TOKEN
  #     - MONGO_DB_HOST=mongodb
